/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Ported from the Stitch "Heritage & Modernity" design system.
        "surface-variant": "#d3e4fe",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9ff",
        "primary-fixed": "#dae2fd",
        "inverse-on-surface": "#eaf1ff",
        "surface-dim": "#cbdbf5",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "surface-container-high": "#dce9ff",
        background: "#f8f9ff",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container": "#e5eeff",
        "on-primary-container": "#7c839b",
        "tertiary-container": "#002113",
        surface: "#f8f9ff",
        "on-surface": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#bec6e0",
        "on-surface-variant": "#45464d",
        "surface-tint": "#565e74",
        "on-tertiary-fixed-variant": "#005236",
        secondary: "#5c5f61",
        "surface-container-low": "#eff4ff",
        "on-tertiary-container": "#009668",
        "tertiary-fixed": "#6ffbbe",
        "on-background": "#0b1c30",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#444749",
        "on-secondary": "#ffffff",
        "inverse-surface": "#213145",
        "primary-fixed-dim": "#bec6e0",
        "secondary-container": "#e0e3e5",
        tertiary: "#000000",
        "outline-variant": "#c6c6cd",
        // Brand overrides from the design system's explicit palette:
        // navy primary + Algerian-green accent used for conversion CTAs.
        primary: "#0f172a",
        outline: "#76777d",
        "on-primary-fixed": "#131b2e",
        "secondary-fixed": "#e0e3e5",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#191c1e",
        "on-secondary-container": "#626567",
        "secondary-fixed-dim": "#c4c7c9",
        "on-error-container": "#93000a",
        // Algerian green accent scale (CTAs / success).
        accent: {
          DEFAULT: "#10b981",
          dark: "#059669",
          tint: "#ecfdf5",
          deep: "#065f46",
        },
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "stack-lg": "32px",
        "stack-md": "16px",
        gutter: "24px",
        "stack-sm": "8px",
        "section-padding": "80px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
        "button-text": ["16px", { lineHeight: "1", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 4px 20px rgba(15, 23, 42, 0.05)",
        "card-hover": "0 10px 30px rgba(15, 23, 42, 0.1)",
        cta: "0 8px 15px rgba(16, 185, 129, 0.3)",
        float: "0 8px 30px rgb(0 0 0 / 0.12)",
      },
      keyframes: {
        "pulse-green-shadow": {
          "0%": { boxShadow: "0 0 0 0 rgba(16, 185, 129, 0.4)" },
          "70%": { boxShadow: "0 0 0 15px rgba(16, 185, 129, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(16, 185, 129, 0)" },
        },
      },
      animation: {
        "pulse-green": "pulse-green-shadow 2s infinite",
      },
    },
  },
  plugins: [],
};
